name: SkyWars
main: org.sobadfish.skywars.SkyWarsMain
version: 2.0-build#1
api:
  - 1.0.11
  - 3.0.0
author: sobadfish & EnderCraft DEV Team
load: POSTWORLD
description: "空岛战争小游戏"

softdepend:
  - ScoreboardPlugin

loadbefore:
  - ScoreboardPlugin
